Remove local idps attribute from Idp python class.
The Idp python class in sibboleth/credentials.py was defining its own set_idps
method that was assigning to the idps attribute - which was clashing with how
jython maps the set_idps method inherited from grixth.sibboleth.IdpObject.

Any attempts to instantiate the Idp python class were failing with

>>> import sibboleth.shibboleth
>>> idp = sibboleth.Idp("UoC")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__pyclasspath__/sibboleth/credentials.py", line 125, in __init__
  File "__pyclasspath__/sibboleth/credentials.py", line 131, in set_idps
AttributeError: read-only attr: idps

It was still possible to instantiate grith.sibboleth.StaticIdpObject.

This commit removes the (otherwise unused) local attributes and accessor
methods from the python Idp class, deferring the handling to the methods
inherited from grixth.sibboleth.IdpObject.